version: "3"
services:

    weather_service:
        build:
          context: .
          dockerfile: ./AppServices/WebAPIService/Dockerfile        
        container_name: weather_service
        restart: unless-stopped
        expose:
          - 5002
        environment: 
          API_KEY: "439d4b804bc8187953eb36d2a8c26a02"
          API_URL: "https://samples.openweathermap.org/data/2.5/weather" 
          ASPNETCORE_ENVIRONMENT: "Development"          
          
     
    angular:
      build:
        context: .
        dockerfile: ./ClientApplications/Angular/Dockerfile        
      container_name: weather_client
      restart: unless-stopped
      ports:
        - 8888:80
      depends_on:       
        - webapi_nginx   


    webapi_nginx:
      build: 
        context: .
        dockerfile: ./AppServices/WebAPIService/nginx/Dockerfile
      container_name: weather_nginx
      restart: unless-stopped
      ports:
        - 5002:8989
      depends_on: 
        - weather_service
